### ISSUE TITLE
No longer supported?

### ISSUE THREAD

**Issue by mrplow** [joefitzgerald/slack-dump#5]
Damn looks like I found this a few months too late. I'm a little surprised this isn't more popular. Any chance anyone is still working on this ?

**Comment by joefitzgerald** [comment]
I'm always open to PRs. And I may begin doing active work on this in the next couple of months.

**Comment by mrplow** [comment]
I'd make a PR if I knew what I was doing but I'm glad to see your looking into it. Thanks!
